apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
spec:
  selector:
    app: tictactoe
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30090
  type: NodePort


